source 'https://rubygems.org'

gem 'rails', '3.2.11' # KEEPS IT AT 3.2.11
gem 'jquery-rails'
gem 'pg'
gem 'thin'
gem 'haml'
gem 'bcrypt-ruby'
gem 'activerecord'
require 'open-uri'
gem 'nokogiri'
gem 'json'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'zurb-foundation', '~> 4.0.0'
end

group :development, :test do
  gem 'coffee-rails-source-maps'

  gem 'factory_girl_rails'
  gem 'guard-rspec'
  gem 'rb-fsevent'

  gem 'rspec-rails'
  gem 'capybara' # TESTING FRAMEWORK FOR WEB BROWSER
  gem 'launchy' # LAUNCHES THE WEB BROWSER WHEN YOU'RE DOING CAPYBARA TESTING
  gem 'database_cleaner' # CLEANS OUT YOUR DATABASE ON EVERY TEST RUN

  gem 'pry-rails'
  gem 'pry-debugger'
  gem 'pry-stack_explorer'

  gem 'annotate'

  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
end