source 'https://rubygems.org'

gem 'rails'
gem 'jquery-rails'
gem 'pg'
gem 'haml'
gem 'activerecord'
gem 'thin'
gem 'httparty'
require 'open-uri'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'zurb-foundation', '~> 4.0.0'
end

group :development, :test do
  gem 'coffee-rails-source-maps'

  gem 'factory_girl_rails'
  gem 'guard-rspec'
  gem 'rb-fsevent'

  gem 'rspec-rails'
  gem 'capybara' # TESTING FRAMEWORK FOR WEB BROWSER
  gem 'launchy' # LAUNCHES THE WEB BROWSER WHEN YOU'RE DOING CAPYBARA TESTING
  gem 'database_cleaner' # CLEANS OUT YOUR DATABASE ON EVERY TEST RUN

  gem 'pry-rails'
  gem 'pry-debugger'
  gem 'pry-stack_explorer'
  gem 'annotate'
  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
end